### ISSUE TITLE
Opmåling af -snit

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#7]
-snit fungerer ikke korrekt. Det skal være muligt at anføre snitnummer, ellers er det ikke muligt at måle flere snit efter hinanden

**Comment by KajFRasmussen** [comment]
Det samme gælder for -sten.

**Comment by KajFRasmussen** [comment]
Jeg kan se nummereringen er gledet bag et punktum i kodebasen, således at følgende fungerer (men ikke er konformt med den oprindelige kodesystematik):
531499.200,6227791.309,71.689,652,-SNIT.1.b58cm d20. diffus nedsivning?
531499.086,6227791.052,71.694,653,-SNIT.1.b58cm d20. diffus nedsivning?
531499.789,6227790.912,71.701,654,-SNIT.1.b58cm d20. diffus nedsivning?
531499.800,6227791.218,71.672,655,-SNIT.1.b58cm d20. diffus nedsivning?
531496.698,6227789.672,71.695,656,-SNIT.2.b45cm d15. diffus nedsivning?
531496.888,6227789.371,71.691,657,-SNIT.2.b45cm d15. diffus nedsivning?
531496.195,6227789.013,71.667,658,-SNIT.2.b45cm d15. diffus nedsivning?
531496.153,6227789.274,71.696,659,-SNIT.2.b45cm d15. diffus nedsivning?

**Comment by KajFRasmussen** [comment]
I version 0.25 virker -snit så slet ikke ???

**Comment by archaeodav** [comment]
Hej Kaj,
_-STEN_ and _-SNIT_ are both set up as per the mapdigi specification, where a sequence of points are measured for each feature with something else (e.g. -KOTE) in between with no ID like the following:

> 701344.787,6157875.809,9.690,50791,-SNIT
701344.827,6157877.853,9.676,50792,-SNIT
701348.757,6157877.857,9.662,50793,-SNIT
701349.189,6157875.689,9.563,50794,-SNIT
701359.429,6157876.471,9.537,50795,-KOTE
701361.034,6157873.436,9.481,50796,-SNIT
701361.298,6157873.741,9.500,50797,-SNIT
701362.871,6157872.623,9.407,50798,-SNIT
701362.647,6157872.344,9.457,50799,-SNIT
701362.626,6157872.360,9.452,50800,-KOTE
701359.677,6157870.677,9.465,50801,-SNIT
701359.854,6157870.900,9.478,50802,-SNIT
701359.275,6157871.494,9.450,50803,-SNIT
701359.048,6157871.314,9.440,50804,-SNIT
701357.243,6157874.938,9.504,50805,-KOTE

It's certainly possible for use snit with an ID, but it requires a delimiter ('.' or ' ') between -_SNIT_ and the number- e.g _-SNIT 1_ rather than _-SNIT1_

**Comment by archaeodav** [comment]
Fixed in version 0.28
